YEAR_START = 2000
YEAR_END = 2024

FIELD_ATENEO = "Ateneo"
FIELD_NOME = "Cognome e Nome"
FIELD_FACOLTA = "Facoltà"
FIELD_FASCIA = "Fascia"
FIELD_GENERE = "Genere"
FIELD_SC = "S.C."
FIELD_SSD = "S.S.D."
FIELD_STRUTTURA = "Struttura di afferenza"
FIELD_AREA = "area"
FIELD_YEAR = "year"



VALUES_ATENEO = {
    'BARI':["università degli studi di bari aldo moro","universita' degli studi di bari aldo moro","universitàdegli studi di bari aldo moro","università degli studi di bari","universita' degli studi di bari",
            "università degli studi aldo moro"],

    'BASILICATA':["università degli studi della basilicata"],

    'BERGAMO':["universita' degli studi di bergamo","unoversità degli studi di bergamo","dipartimenti dell'università degli studi di bergamo","università di bergamo","università degli studi di bergamo",
               "uniersità degli studi di bergamo"],
    
    'BOLOGNA':["universita' di bologna","università di bologna","universita' di bologgna","universita' dibologna","alma mater studiorum universita' di bologna","alma mater studiorum università di bologna",
               "alma mater strudiorum università di bologna","alma mater studiorum -universita' di bologna","alma mater studiorum","apos-ufficio concori docenti","alma mater studiorum "],

    'BRESCIA':["università degli studi di brescia","universita’ degli studi di brescia","university of brescia","università  degli studi di brescia","universitaì' degli studi di brescia",
               "universita' degli studi di brescia","università degli studi brescia","universita' degli studi di brescia dipartimento di scienze cliniche e sperimentali","universtita' degli studi di brescia"],

    'Bocconi MILANO':["universita commerciale luigi bocconi","università commerciale l.bocconi","università commericale luigi bocconi","università commerciale luigi bocconi",
                      "università bocconi","bocconi university"],
    
    '"Ca\' Foscari" VENEZIA':["università ca' foscari venezia","università ca' foscari"],

    'CAGLIARI':["universita' degli studi di cagliari","università di cagliari","università degli studi di cagliari","university of cagliari"],
    
    'CAMERINO':["università degli studi di camerino (convenzione con infn perugia)","universita' degli studi di camerino","università degli studi di camerino","università di camerino","università degli studi di  camerino",
                "scuola di scienze e tecnologie unicam, sezione di fisica"],
    
    'CAMPANIA - "L. VANVITELLI"':["università degli studi della campania","seconda università degli studi di napoli"],

    'CASD - Scuola Superiore':["centro alti studi per la difesa (casd)","centro alti studi per la difesa","centro alti studi difesa scuola superiore universitaria"],

    'CASSINO e LAZIO MERIDIONALE':["università degli studi di cassino e del lazio meridionale","università degli studi  di cassino e del lazio meridionale","università di cassino e del lazio meridionale","universita’ degli studi di cassino e del lazio meridionale","università degli studi di cassino e del lazio meridionale dipartimento di economia e giurisprudenza",
                                   "università degli studi di cassino e lazio meridionale"],

    'CATANIA':["università degli studid di catania","u/niversità degli studi di catania","università di catania","università deglistudi di catania","università degli stud di catania",
               "università degli studi di catania","universita' degli studi di catania","universaità degli studi di catania","università degli studi di caatania","università degli studi di catani,"
               "università degli studidi catani","università degli studi di catani","università degli studidi catani"],
    
    'CATANZARO':["università degli studi magna graecia di catanzaro","university of catanzaro"],

    'CHIETI-PESCARA':["università degli studi chieti pescara","università degli studi g.d'annunzio chieti-pescara","università degli studi di chieti pescara","universita' degli studi chieti-pescara","università degli studi di chieti-pescara","università degi studi di chieti-pescara",
                      "università egli studi di chieti-pescara","università degli studi chieti-pescara","università g. d'annunzio di chieti-pescara",'università"g. d\'annunzio" chieti-pescara',"universita' degli studi di chieti-pescara",
                      "università degli studi  di chieti-pescara",'università degli studi “g. d’annunzio” di chieti-pescara',"università deglli studi chieti-pescara","università g. d'annunzio chieti pescara",
                      "università degli studi g. d'annunzio","università degli studi g. d'annunzio ch-pe",'università degli studi "g. d\'annunzio" ch-pe',"università gabriele d'annunzio",'università degli studi "g. d\'annunzio ch-pe',
                      "università degli studi chieti","universita' degli studi chieti","universita' degli studi di chieti","università degli studi di chieti"],

    'Cattolica del Sacro Cuore':["universita' cattolica del sacro cuore","università cattolica del sacro cuore","università cattolica delo sacro cuore","universita' cattolica del sacro cuor","università cattolica del sacro cuole"],

    'della CALABRIA':["universita' della calabria","univeristà della calabria","univesità della calabria","università della calabria",""],
    
    'EUROPEA di ROMA':[],

    'FERRARA':["università degli studi di ferrara- dip.to di medicina traslazionale e per la romagna","università degli studi di ferrara- dip.to di studi umanistici","università egli studi di ferrara","universita' di ferrara","universita' degli studi di ferrara","universita di ferrara",
               "universita di ferrara-dip.to di fisica","universita di ferrara-dip.to economia istituzioni e territorio","università degli studi di ferrara dip.to di studi umanistici","università degli studi di ferrara-  dip.to di studi umanistici",
               "università degli studi di ferrara- dipartimenti di medina traslazionale e per la romagna","universtà degli studi di ferrara","univeristà degli studi di ferrara",
               "università degli studi di ferrara- dipartimento di matematica e informatica","università degli studi di ferrara- dipartimento di scienze della vita e biotecnologie",
               "università degli studi di ferrara- dipartimento di studi umanistici","università degli studi di ferrara- dipartimento di architettura","università degli studi di ferrara –department of law","università degli studi di ferrara",
               "università degli studi di ferrara- dipartimento di fisica e scienze della terra"],

    'FIRENZE':["università degli studi di firenze", "universita’ degli studi di firenze ", "universita’ degli studi di firenze","università degli studi di firenze unità di processo amministrazione del personale docente e ricercatore",
               "università degli studi di firenze -","organizzazione/ente *	università degli studi di firenze","università degli studi di firenze- dipartimento di scienze della terra",
               "dipartimento di biologia evoluzionistica dell'università degli studi di firenze","università degli sudi di firenze","università di firenze",
               "dipartimento sistemi e informatica, università degli studi di firenze","universita' degli studi di firenze","università degli studi di firenze- dipartimento di scienze della salute",
               "università degli studi di firenze- dipartimento di scienze delle produzioni agroalimentari e dell'ambiente","università degli studi di firenze- dipartimento di scienze giuridiche",
               "università degli studi di firenze- dipartimento di scienze per l'economia e l'impresa","università degli studi di firenze- dipartimento di storia, archeologia, geografia, arte e spettacolo",
               "università degli studi di firenze- dipartimento di architettura-disegno, storia, progetto","università  degli studi di firenze- dipartimento di diritto pubblico","università degli studi di firenze- dipartimento di fisica e astronomia",
               "università degli studi di firenze- dipartimento di economia, ingegneria, scienze e tecnologie agrarie e forestali (deistaf)","università degli studi di firenze- dipartimento di italianistica",
               "università degli studi di firenze- dipartimento di medicina interna","università degli studi di firenze- dipartimento di psicologia","università degli studi di firenze- dipartimento di scienze aziendali",
               "università degli studi di firenze- dipartimento di scienze dell'educazione e dei processi culturali e formativi","università degli studi di firenze- dipartimento di scienze fisiologiche",
               "università degli studi di firenze- dipartimento di scienze per la salute della donna e del bambino","università degli studi di firenze- dipartimento di statistica","università degli studi di firenze- dipartimento di studi sullo stato",
               "università studi firenze","università  studi  firenze","università degli studi di firenae"],
    
    'FOGGIA':["università di foggia","università degli studi di foggia","universita' di foggia"],
    
    'GENOVA':["università degli studi di genova","universita di genova","università degli studi genova","universita' degli studi di genova","università degli srtudi di genova","universita' di genova","università degli stusi di genova",
              "università di genova","university of genoa"],
    
    'Gran Sasso Science Institute':["gran sasso science institute"],

    'HUMANITAS University':["humanitas university","humanitas univesrity"],

    'I.U.S.S. - PAVIA':["istituto universitario di studi superiori di pavia","scuola universitaria superiore iuss pavia","istituto universitario di studi superiori pavia",
                        "istituto universitario di studi superiori"],
    
    'INSUBRIA':["università degli studi dell'insubria"],
    
    'IULM - MILANO':["libera università di lingue e comunciazione iulm","libera università di lingue e comunicazione iulm"],
    
    'L\'AQUILA':["università degli sstudi dell'aquila", "università degli studi dell'aquila","universita' degli studi dell'aquila","settore concorsi e selezioni"],
    
    '"L\'Orientale" di NAPOLI':["università degli studi di napoli l'orientale","universita' degli studi di napoli l'orientale","universita' l'orientale",
                                "università degli sudi di napoli l'orientale","università l'orientale","università dgli studi di napoli l'orientale","università deli studi di napoli l'orientale",
                                "universita' orientale"],
    
    'LINK CAMPUS':["università degli studi link campus university","link campus university"],
    
    'LIUC - CASTELLANZA':["università carlo cattaneo"],
    
    'LUM "Giuseppe Degennaro"':["università lum",'università lum "giuseppe degennaro"',"lum giuseppe degennaro","universita' lum jean monnet","università lum jean monnet"],

    'Libera Univ. "Maria SS.Assunta"-LUMSA - ROMA':["libera universita' maria ss assunta","lumsa libera universita' maria ss assunta","lumsa universita'","universita' lumsa"],
    
    'Libera Università di BOLZANO':["libera universitá di bolzano","libera università di bolzano"],

    'Luiss Guido Carli':["luiss guido carli","luiss libera università internazionale degli studi sociali guido carli"],
    
    'MACERATA':["univeristà degli studi di macerata","università degli studi di macerata"],

    'MESSINA':["università degli studi di messina","universita' degli studi di messina"],

    'MILANO':["università degli studi di milano -dipartimento di diritto pubblico italiano e sovranazionale","università degli studi di milano -dipartimento di biotecnologie mediche e medicina traslazionale","università degli studi di milano -dipartimento di scienze agrarie e ambientali",
              "univ degli studi di milano",'università degli studi di milano -dipartimento di fisica “aldo pontremoli”',"università degli studi di milano -dipartimento di scienze della terra","università degli studi di milano -dipartimento di scienze e politiche ambientali",
              "università degli studi di milano -dipartimento di scienze farmaceutiche","università degli studi di milano -dipartimento di scienze veterinarie per la salute, la produzione animale e la sicurezza alimentare",
              "università degli studi di milano -dipartimento di studi internazionali, giuridici e storico-politici","università degli studi di milano -dipartimento di studi storici","niversità degli studi di milano",
              "università degli studi di milano -dipartimento di beni culturali e ambientali","uuniversità degli studi di milano -dipartimento di scienze sociali e politiche","uuniversità degli studi di milano -dipartimento di scienze biomediche, chirurgiche e odontoiatriche",
              "università degli studi di milano -dipartimento di scienze della mediazione linguistica e di studi interculturali",'università degli studi di milano -dipartimento di scienze biomediche e cliniche “l. sacco”',
              "università degli studiuniversità degli studi di milano","università degli studi di milano -dipartimento di scienze delle salute",'niversità degli studi di milano -dipartimento di scienze della terra “ardito desio”',
              "univ. studi di milano","università degli studi di milano -dipartimento di lingue e letterature straniere","università degli studi di milano -dipartimento di scienze sociali e politiche",
              "università degli studi di milano -dipartimento di scienze cliniche e di comunità","università degli studi di milano -dipartimento di scienze biomediche e cliniche","università degli studi di milano -dipartimento di fisiopatologia medico-chirurgica e dei trapianti",
              "università degli studi di milano -dipartimento di matematica","università degli studi di milano -dipartimento di economia, management e metodi quantitativi","università degli studi di milano -dipartimento di medicina veterinaria",
              "università degli studi di milano -dipartimento di oncologia ed emato-oncologia","università degli studi di milano -dipartimento di scienze agrarie e ambientali- produzione, territorio, agroenergia",
              "università degli studi di milano -dipartimento di scienze della salute","università degli studi di milano -dipartimento di studi letterari, filologici e linguistici","università degli studi di milano -dipartimento di scienze biomediche per la salute",
              "università degli studi di milano -dipartimento di informatica","università degli studi di milano -dipartimento di scienze per gli alimenti, la nutrizione e l'ambiente","università degli studi di milano -dipartimento di bioscienze",
              "università degli studi di milano -dipartimento di filosofia","università degli studi di milano -dipartimento di scienze giuridiche","università degli studi di milano -dipartimento di fisica","università degli studi di milano -dipartimento di diritto privato e storia del diritto",
              'università degli studi di milano -dipartimento di filosofia “piero martinetti”',"università degli studi di milano -dipartimento di chimica",'università degli studi di milano -dipartimento di scienze della terra “ardito desio”',
              "università degli studi di milano -dipartimento di scienze farmacologiche e biomolecolari","università degli studi di milano -dipartimento di scienze biomediche, chirurgiche e odontoiatriche","negotiable  università degli studi di milano",
              'dipartimento di scienze della terra “ardito desio”','dipartimento di scienze giuridiche “cesare beccaria”','dipartimento di matematica “federigo enriques”','dipartimento di scienze giuridiche “c. beccaria”',
              'dipartimento di scienze biomediche e cliniche “l. sacco”','dipartimento di informatica “g. degli antoni”','dipartimento di informatica “giovanni degli antoni”',"dipartimento di scienze biomediche per la salute",
              "dipartimento di scienze sociali e politiche","dipartimento di scienze cliniche e di comunità","dipartimento di fisiopatologia medico-chirurgica e dei trapianti"],

    'MILANO-BICOCCA':["università degli studi di milano", "università degl istudi di milano bicocca","università degli studi di milano-bicocca","università degli studi di milano bicocca"],
    
    'MODENA e REGGIO EMILIA':["università degli studi di modena e reggio emilia","universita' degli studi di modena e reggio emilia","università di modena e reggio emilia","universita' di modena e reggio emilia",
                              "università deli studi di modena e reggio emilia"],

    'MOLISE':["university of molise","università degli studi del molise"],
    
    'Mediterranea di REGGIO CALABRIA':["università mediterranea di reggio calabria","università degli studi mediterranea di reggio calabria","universita' mediterranea di reggio calabria","dipartimento biomaa"],
    
    'Napoli Federico II':["università degli studi di napolifederico ii","unioversità degli studi di napoli federico ii","università degli studi di napoli federico ii","univrsità degli studi di napoli federico ii","università degli stufi di napoli federico ii",
                          "università degli studi di napoli fedrico ii","univerrsità degli studi di napoli federico ii","università degli studi napoli federico ii","università degli studi di napoli federico","università degli studi di napoli federico i",
                          "università di napoli federico ii","università degli studi federico ii di napoli","università federico ii","università degli studi federico ii","università degli studi di napoli federico ii -",
                          "università degli studi di napoli federco ii","università studi di napoli","università degli studi di napoli","universita' degli studi di napoli"],

    'PADOVA':["università degli studi di padova dimed", "università degli studi di padova dii", "inaf-oa padova", "università degli studi di padova- dip dissgea", "università degli studi di padova- dip di matematica- dm",
              "università degli studi di padova- dip di scienze chimiche", "università degli studi di padova- dip sdb", "università degli studi di padova- dip dpss",
              "univesrità degli studi di padova", "università degli studi di padova -", "università degli studi di padova", "università degli studi di padova- dip di fisica e astronomia", "università degli studi di padova- dip di biologia",
              "università degli studi di padova- dip di matematica", "università degli studi di padova- dip di medicina","università degli studi di padova- dip di psicologia dello sviluppo e della socializzazione",
              "univesità degli studi di padova", "universita' degli studi di padova","università degli studi di padova dipartimento di salute della donna e del bambino", "università degli studi di padova- dip di ingegneria industriale- dii",
              "università degli studi di padova- dip di studi linguistici e letterari-disll", "università degli studi di padova- dip scienze del farmaco-dsf", "università degli studi di padova- dip di geoscienze", "università degli studi di padova- dip di tecnica e gestione dei sistemi industriali-dtg",
              "università degli studi di padova- dip di ingegneria dell'informazione", "università degli studi di padova- dip di scienze cardiologiche toraciche e vascolari -dsctv", "università degli studi di padova-dipartimento dafnae",
              "università degli studi di padova-dipartimento tesaf", "università degli studi di padova-dipartimento disc", "università degli studi di padova-dipartimento dfa", "università degli studi di padova-dipartimento dipic",
              "università degli studi di padova- dip di scienze chirurgiche oncologiche e gastroenterologiche -discog", "università degli studi di padova- dip. di ingegneria dell'informazione -dei", "università degli studi padova",
              "università degli studi di padova -dip. di diritto privato e critica del diritto", "università degli studi di padova ", "università degli studi di padova dip.to di medicina molecolare",
              "università degli studi di padova dip.to di ingegneria dell'informazione dei", "università degli studi di padova- dip di ingegneria dell'informazione dei", "università degli studi di padova- dip di medicina molecolare",
              "università degli studi di padova- dip di neuroscienze- dns", "università degli studi di padova- dip di imatematica -dm", "università degli studi di padova- dip di scienze economiche e aziendali dsea",
              "università degli studi di padova- dip di filosofia sociologia pedagogia e psicologia applicata -fisppa", "università degli studi di padova- dip di ingegneria civile, edile e ambientale-icea", "università degli studi di padova- dip di medicina animale, produzioni e salute -maps",
              "università degli studi di padova- dip  di psicologia dello sviluppo e della socializzazione -dpss", "università degli studi di padova- dip di scienze biomediche dsb", "università degli studi di padova- dip di scienze storiche, geografiche e dell'antichità dissgea",
              "università degli studi di padova- dip di scienze del farmaco", "università degli studi di padova- dip dei beni culturali: archeologia, storia dell'arte, del cinema e della musica -dbc", "università degli studi di padova- dip di scienze statistiche", "università degli studi di padova -dsb"],

    'PALERMO':["università degli studi di palermo", "università di palermo", "university of palermo", "università degi studi di palermo"],
    
    'PARMA':["università degli studi di parma", "università deghli studi di parma", "università degli studi di parmacc", "univeristà degli studi di parma", "universita’ degli studi di parma", "universita' degli studi di parma",
             "università di parma", "universita' di parma","universita' degli studi di aprma"],

    '"Parthenope" di NAPOLI':['università degli studi di napoli "parthenope"',"universita degli studi di napoli parthenope","universita' parthenope","universita parthenope","università degli studi di napoli parthenope",
                              "universita' degli studi di napoli parthenope","universita' parthenope di napoli","università parthenope di napoli","università degli studi di napoli parhenope"],

    'PAVIA':["università degli stud di pavia","university of  pavia","università degli studi di pavia",],

    'PERUGIA':["universita degli studi di perugia","universita'  degli  studi di perugia","università degli stidi di perugia","università degli studi di perugia","universita' degli studi di perugia","universita’ degli studi di perugia","università degli studi perugia"],
    
    'PIEMONTE ORIENTALE':["universita' degli studi del piemonte orientale","universita' del piemonte orientale","università piemonte orientale","universita del piemonte orientale","università del piemonte orientale",
                          "università  del piemonte orientale- dipartimento di medicina traslazionale","università del piemonte orientale- dipartimento di scienze della salute","università  del piemonte orientale",
                          "università del piemonte orientale-","università degli studi del piemonte orientale- dipartimento di studi per l’economia e l’impresa.",'università degli studi del piemonte orientale “amedeo avogadro”',
                          'università degli studi del piemonte orientale “amedeo avogadro”- dipartimento di scienze del farmaco',"università degli studi del piemonte orientale"],
    
    'PISA':["scuola superiore sant'anna di pisa","scuola superiore sant'anna  pisa","sant'anna scuola universitaria superiore pisa","università di pisa","scuola superiore sant'anna pisa"],

    'Politecnica delle MARCHE':["università politecnica delle marche","universita' politecnica delle marche"],

    'Politecnico di BARI':["politecnico di bari -- dipartimento interateneo di fisica","politecnico di bari --- dipartimento di ingegneria elettrica e dell’informazione/dipartimento di meccanica, matematica e management","politecnico di bari --- dipartimento di meccanica, matematica e management",
                           "politecnico di bari --- dipartimento di scienze dell'ingegneria civile e dell'architettura","politecnico di bai","politecnico di bari"],
    
    'Politecnico di MILANO':["politecnico di milano","politecnico di millano","politecnico di milan","politecnico di  milano"],

    'Politecnico di TORINO':["politecnico di torino","politecnico ditorino"],

    'ROMA "Foro Italico"':["universita' degli studi di roma  foro italico","università degli studi di roma foro italico","università foro italico"],

    'ROMA "La Sapienza"':["sapienza università di roma","sapienza universsità di roma","sapienza università di roma-dip. fisiologia e farmacologia","università la sapienza dip. biotecnologie cell. ed ematologia",
                          "la sapienza universita' di roma dip. medicina interna e specialita' mediche", "la sapienza università la sapienza", "università sapienza dipartimento di scienze di base e applicate per l'ingegneria",
                          "università la sapienza  dipartimento medicina molecolare", "la sapienza università di roma", "università di roma sapienza","sapienza universita’ di roma",
                          "dipartimento di medicina molecolare sapienza università di roma", "sapienza università di roma -dip. fisiologia e farmacologia", "sapienza university of rome -dept. of physics",
                          "sapienza università di roma, dipartimento di scienze odontostomatologiche e maxillo facciali",'università degli studi di roma “la sapienza”',"scola di ingegneria aerospaziale sapienza università di roma",
                          "dip biologia e biotecnologie c.darwin sapienza univ roma", "sapienza universita' di roma-dipartimento di psicologia dinamica e clinica", "universita' la sapienza", "sapienza_università di roma",
                          "dipartimento di psicologia dinamica e clinica sapienza universita' di roma", "università di roma la sapienza dipartimento di scienze politiche", "università di roma l a sapienza dipartimento di scienze giuridiche",
                          "università di roma la sapienza dipartimento di scienze giuridiche", "dipartimento scienze dell'antichità -sapienza università di roma","la sapienza","universita' sapienza dipartimento dicea",
                          "dipartimento di medicina clinica e molecolare università degli studi di roma la sapienza", "sapienza universita' roma","dipartimento di neuroscienze umane- sapienza università di roma",
                          "università roma la sapienza dipartimento di ingegneria civile edile e ambientale","dipartimento di ingegneria strutturale e geotecnica, sapienza roma","sapienza university in rome",
                          "università la sapienza dipartimento di scienze di base e applicate per l'ingegneria", "dip. ingegneria meccanica e aerospaziale-sapienza università di roma","dipartimento di studi giuridici ed economici sapienza università di roma",
                          "sapienza universita' di roma-dipartimento di psicologia dinamicaclinicae salute","sapienza universita' di roma-dipartimento psicologia","dipartimento di medicina sperimentale sapienza università di roma",
                          "università la sapienza dipartimento di medicinaclinica e molecolare","sapienza università di roma dipartimento di medicina clinica e molecolare","sapienza università di roma dipartimento di medicina molecolare",
                          "università la sapienza roma","dip. di neuroscienze salute mentale e organi di senso nesmos sapienza università di roma","sapienza, università di roma","sapienza università di roma- dipartimento di sanità pubblica e malattie infettive",
                          "universita' degli studi di roma la sapienza",'"sapienza" università di roma',"dipartimento di scienze statistiche sapienza universita' di roma","sapienza università di roma  dipartimento di architettura e progetto",
                          "università di roma sapienza dip. si sanità pubblica e malattie infettive","sapienza universita' di roma dipartimento psicologia","univ. di roma sapienza","universita sapienza","sapienza-università di roma",
                          "università sapienza","dipartimento di scienze chirurgiche università di roma la sapienza","la sapienza dipartimento di scienze di base e applicate per l'ingegneria","sapienza università di roma dipartimento di fisica",
                          "universita' la sapienza di roma","dip. di ingegneria informatica automatica e gestionale a. ruberti sapienza università di roma","sapienza università di roma- dip. memotef","università degli studi la sapienza roma","universita' sapienza di roma",
                          "universita' degli studi di roma la sapienza dipartimento di medicina molecolare","dipartimento di diritto ed economia delle attività produttive, sapienza università di roma","università di roma sapienza dipartimento di economia e diritto",
                          "universita' di roma la sapienza-dip.biol.ambientale","dip. scienze anatomiche, istologiche, medico-legali e dell'apparato locomotore/ sapienza università di roma","universita' sapienza","universita sapienza di roma","dipartimento di scienze sociali ed economiche sapienza università di roma",
                          "dipartimento di storia antropologia religioni arte spettacolo di sapienza università di roma","dipartimento di fisica- universita sapienza","dipartimento di scienze statistiche, sapienza università di roma",
                          "universita' di roma la sapienza","sapienza università  roma dipartimento diet","department of radiological sciences oncology and pathological anatomy of the sapienza university of rome",
                          "dipartimento di medicina clinica e molecolare di sapienza università degli studi di roma",'università degli studi di roma "la sapienza"',"sapienza università di roma dipartimento metodi e modelli per l'economia, il territorio la finanza",
                          "università sapienza roma","dipartimento di ingegneria meccanica e aerospaziale/sapienza università di roma","dip. studi giuridici ed economici sapienza univ. di roma","dipartimento di psicologia sapienza università di roma",
                          "sapienza università  roma  dipartimento di ingegneria dell’informazione, elettronica e telecomunicazioni","sapienza universita' di roma-dipartimento di psicologia dinamica clinica e salute","dipartimento di psicologia sapienza universita' di roma",
                          "dipartimento di neuroscienze salute mentale ed organi di senso la sapienza università","dipartimento di fisica- sapienza università di roma","dipartimento di biotecnologie cellulari ed ematologia dell'università la sapienza di roma",
                          "università la sapienza dipartimento di medicina molecolare","sapienza università di roma dip. di ingegneria meccanica e aerospaziale","università degli studi di roma la sapienza","università la sapienza di roma","sapienza","sapienza università di roma  dipartimento di medicina sperimentale",
                          "dipartimento di scienze sociali ed economiche università degli studi di roma la sapienza","università di roma la sapienza dipartimento di neuroscienze salute mentale e organi di senso","physics dept. sapienza university of rome","università sapienza di roma",
                          "dip. ingegneria meccanica aerospaziale/sapienza università di roma","dpt neurology and psychiatry neurosurgery, sapienza university of rome","sapienza universita' di roma","dipartimento di informatica dell'universita' degli studi di roma la sapienza",
                          "sapienza università di roma dipartimento di psicologia","sapienza università dipartimento di fisica","dipartimento di economia e diritto della sapienza università di roma","dipartimento di fisica sapienza università di roma","sapienza universita  di roma-dip. scienze statistiche",
                          "sapienza università di roma- dipartimento memotef","dipartimento di ingegneria strutturale e geotecnica, sapienza università di roma","sapienza università degli studi di roma","università sapienza dipartimento di medicina sperimentale",
                          "università la sapienza","dipartimento di ingegneria stutturale e geotecnica, sapienza università di roma","università degli studi di roma sapienza","sapienza università di roma dipartimento di architettura e progetto","sapienza università",
                          "sapienza universita di roma","dipartimento di fisiologia e farmacologia sapienza università di roma","universita' degli studi di roma la sapienza -dipartimento di scienze dell'antichita'","dipartimento di fisica sapienza università",
                          "sapienza universita' di roma-dipartimento di psicologia dinamicaclinica e salute","dipartimento di fisica sapienza","dipartimento ingegneria meccanica e aerospaziale sapienza università di roma",
                          "dipartimento saras sapienza università di roma","università di roma la sapienza","dipartimento di comunicazione e ricerca sociale, sapienza università di roma","dipartimento ingegneria astronautica, elettrica, energetica (diaee) sapienza",
                          "sapienza universita di roma dipartimento di biologia ambientale","sapienza università di roma dipartimento di medicina sperimentale","sapienza università di roma dipartimento di scienze sociali ed economiche","dipartimento di scienze cliniche internistiche, anestesiologiche e cardiovascolari -sapienza università di roma",
                          "dipartimento di ingegneria astronautica elettrica ed energetica università degli studi di roma","saspienza universita' di roma","sapeinza università di roma"],
    
    'ROMA "Tor Vergata"':['“università degli studi di roma “tor vergata”','università degli studi di roma “tor vergata”',"università degli studi di roma tor vergata",'università degli studi di roma "tor vergata"',"universita degli studi di roma tor vergata",'università degli studi di roma “tor vergata',
                          'università degli studi di roma “tor vergat'],

    'ROMA TRE':["università degli studi roma tre"],

    'S. Raffaele MILANO':["università vita-salute s. raffaele di milano","università vita-salute san raffaele di milano","università vita-salutesan raffaele","università vita-salute san raffaele milano","università vita-salute san raffaele"],
    
    'SALENTO':["university of salento","università del salento dipartimento di ingegneria dell'innovazione","università del salento","università del salento, dipartimento di scienze e tecnologie biologiche e ambientali","università del salento, dipartimento di studi umanistici"],

    'SALERNO':["univerisità degli studi di salerno","università degli studi di salerno","università di salerno","universitàdegli studi di salerno","universita degli studi di salerno",
               "univesità degli studi di salerno","univeristà degli studi di salerno"],
    
    'SANNIO di BENEVENTO':["universita' degli studi del sannio","universita degli studi del sannio","universita' degli  studi del sannio"],

    'SASSARI':["dipartimento di giurisprudenza dell'università degli studi di sassari","università degli studi di sassari","università degli studi di  sassari",
               "università degli stud di sassari-dipartimento di scienze mediche, chirurgiche e sperimentali","università deli studi di sassari","università di sassari",
               "università degi studi di sassari","dipartimenti dell'università degli studi di sassari"],
    
    'SCIENZE GASTRONOMICHE':["università degli studi di scienze gastronomiche","universita' degli studi di scienze gastronomiche","università scienze gastronomiche","università degli studi di scienze gastronomiche di pollenzo"],

    'SIENA':["università di siena","universita' degli studi di siena","università degli studi di sienas","università degli studi di siena"],

    'SISSA - TRIESTE':["sissa","scuola internazionale superiore di studi avanzati"],
    
    'SUM - Ist. Italiano di SCIENZE UMANE FIRENZE':[],

    'Scuola IMT - LUCCA':["imt lucca"],
    
    'Scuola IMT Alti Studi LUCCA':["scuola imt alti studi lucca","imt institute for advanced studies lucca","imt alti studi lucca","imt school for advanced studies lucca",
                                   "imt school for advanced studies"],
    
    'Scuola Normale Superiore di PISA':["scuola normale superiore pisa","scuola normale superiore ","scuola normale superiore -classe di scienze umane","scuola normale superiore -classe di scienze matematiche e naturali",
                                        "scuola normale superiore -classe di lettere e filosofia","scuola normale superiore","scuola normale superiore -classe di scienze"],

    'Scuola Superiore Meridionale':["scuola superiore meridionale"],

    'Scuola Superiore Sant\'Anna':["scuola supeeriore sant'anna","scuola superiore sant'anna","scuola superiore sant'anna istituto tecip","scuola superiore sant'anna istituto di biorobotica","scuola superiore sant'anna istituto dirpolis"],

    'Stranieri REGGIO CALABRIA':["università per stranieri dante alighieri reggio calabria","università per stranieri dante alighieri di reggio calabria","università per stranieri dante alighieri","università per stranieri"],
    
    'Stranieri di PERUGIA':["università per stranieri di perugia"],

    'Stranieri di SIENA':["università per stranieri di  siena","università per stranieri di siena- dipartimento di studi umanistici","università per stranieri di siena"],
    
    'Suor Orsola Benincasa - NAPOLI':["universita' degli studi suor orsola benincasa","università degli studi suor orsola benincasa","universita' suor orsola benincasa","università suor orsola benincasa","universita degli atudi suor orsola benincasa",
                                      "universita' degli studi suor orsola benincasa -napoli"],

    'TERAMO':["universita'  degli studi di teramo","universita' di teramo","università di teramo","universita di teramo","university of teramo",
              "università degli studi di teramo","universita' degli studi di teramo"],
    
    'TORINO':["universita' degli studi di torino","universita' di torini","universita' degli studi dii torino","università degli studi di torino","universita' di torino",
              "universita’ degli studi di torino","universita'  di torino"],

    'TRENTO':["university of trento",".university of trento","university of trento  -department of sociology and social research","università di trento",
              "university of trento faculty of law","university of trento- center agriculture food environment"],

    'TRIESTE':["università degli studi di trieste","univerità degli studi di trieste","university of trieste"],
    
    'TUSCIA':["università degli studi della tuscia","univeristà degli studi della tuscia"],

    'UDINE':["university of udine","università degli studi di udine"],

    'UKE - Università Kore di ENNA':["università degli studi di enna","università kore di enna"],
    
    'UNICUSANO - Telematica Roma':["universita' niccolo' cusano telematica roma", 'unicusano università degli studi "niccolò cusano"',"università degli studi niccolò cusano telematica roma",
                                   "universita' degli studi unicusano -telematica roma","universita' degli studi unicusano","unicusano università degli studi","universita' unicusano roma",
                                   "unicusano","università niccolo cusano","università niccolò cusano","università degli studi niccolò cusano","unicusano universita' roma","universita' degli studi niccolo' cusano",
                                   "universita' degli studi niccolo' cusano telematica roma","universita' niccolo' cusano"],
    
    'UNISR - San Raffaele':[],
    
    'UniCamillus':["università unicamillus","unicamillus","unicamillus università"],

    'UniCamillus - Saint Camillus International U':[],

    'Univ. "Campus Bio-Medico" di ROMA':["università campus bio-medico","università campus bio -medico di roma","università campus bio-medico di roma"],
    
    'Univ. Studi GUGLIELMO MARCONI - Telematica':['università degli studi di roma “g. marconi”',"università degli studi  'guglielmo marconi'",'università degli studi "guglielmo marconi"',"università degli studi 'guglielmo marconi'",
                                                  "università degli studi guglielmo marconi"],
    
    'Univ. Studi Internazionali di ROMA (UNINT)':["università degli studi internazionali di roma unint","unint","università degli studi internazionali di roma -unint","università degli studi internazionali di roma"],

    'Univ. Telematica "E-CAMPUS"':["università telematica ecampus","università ecampus","c/o università ecampus"],
    
    'Univ. Telematica "GIUSTINO FORTUNATO"':["universita' telematica giustino fortunato","università degli studi giustino fortunato","univwersita' telematica giustino fortunato"],

    'Univ. Telematica "LEONARDO da VINCI"':["università telematica leonardo da vinci","università telematica leonardo da vinci (unidav)"],

    'Univ. Telematica "Universitas MERCATORUM"':["univeristas mercatorum","università telematica mercatorum","unimercatorum","universitas mercatorum","università telematica universitas mercatorum",
                                                 "università mercatorum","universita' telematica mercatorum",'università telematica “universitas mercatorum”'],
    
    'Univ. Telematica IUL':["università telematica degli studi iul","universita’ telematica degli studi iul","universita telematica degli studi iul","italian university line"],
    
    'Univ. Telematica Internazionale UNINETTUNO':["università telematica internazionale uninettuno","universita' telematica internazionale uninettuno"],

    'Univ. Telematica PEGASO':["università telematica pegaso","università telematica pegaso srl","universirà telematica pegaso","università telematica pegsao"],
    
    'Univ. Telematica San Raffaele Roma':["universita' telematica san raffaele roma","universita' telematica san raffaele roma s.r.l.","università telematica san raffaele roma"],

    'Univ. Telematica UNITELMA SAPIENZA':["università deglki studi di roma unitelma sapienza","universita' degli studi di roma unitelma sapienza",'università degli studi di roma "unitelmasapienza"',
                                          "università degli studi di roma unitelma sapienza","unitelmasapienza","unitelma sapienza"],

    'Università IUAV di VENEZIA':["universita' iuav di venezia","università iuav di venezia","universita’ iuav di venezia","universita iuav di venezia"],

    'Università degli Studi di Roma UnitelmaSapie':[],

    'Urbino Carlo Bo':["università degli studi di urbino carlo bo","università degli studi carlo bo"],

    'VALLE D\'AOSTA':["università della valle d'aosta-université de la vallée d'aoste","università della valle d'aosta","università della valle d'aosta université de la vallée d'aoste"],

    'VERONA':["università di verona","universita' degli studi di verona","università degli studi di verona","university of verona","universita' di verona"]
}





VALUES_SSD_PER_AREA = {
    '01 - Scienze matematiche e informatiche': ['INF/01', 'MAT/01', 'MAT/02', 'MAT/03', 'MAT/04', 'MAT/05', 'MAT/06', 'MAT/07', 'MAT/08', 'MAT/09'],
    '02 - Scienze fisiche': ['FIS/01', 'FIS/02', 'FIS/03', 'FIS/04', 'FIS/05', 'FIS/06', 'FIS/07', 'FIS/08'],
    '03 - Scienze chimiche': ['CHIM/01', 'CHIM/02', 'CHIM/03', 'CHIM/04', 'CHIM/05', 'CHIM/06', 'CHIM/07', 'CHIM/08', 'CHIM/09', 'CHIM/10', 'CHIM/11',
        'CHIM/12'],
    '04 - Scienze della Terra': ['GEO/01', 'GEO/02', 'GEO/03', 'GEO/04', 'GEO/05', 'GEO/06', 'GEO/07', 'GEO/08', 'GEO/09', 'GEO/10', 'GEO/11', 'GEO/12'],
    '05 - Scienze biologiche': ['BIO/01', 'BIO/02', 'BIO/03', 'BIO/04', 'BIO/05', 'BIO/06', 'BIO/07', 'BIO/08', 'BIO/09', 'BIO/10', 'BIO/11', 'BIO/12',
        'BIO/13', 'BIO/14', 'BIO/15', 'BIO/16', 'BIO/17', 'BIO/18', 'BIO/19'],
    '06 - Scienze mediche': ['MED/01','MED/02','MED/03','MED/04','MED/05','MED/06','MED/07','MED/08','MED/09','MED/10','MED/11','MED/12','MED/13',
        'MED/14','MED/15','MED/16','MED/17','MED/18','MED/19','MED/20','MED/21','MED/22','MED/23','MED/24','MED/25','MED/26',
        'MED/27','MED/28','MED/29','MED/30','MED/31','MED/32','MED/33','MED/34','MED/35','MED/36','MED/37','MED/38','MED/39',
        'MED/40','MED/41','MED/42','MED/43','MED/44','MED/45','MED/46','MED/47','MED/48','MED/49','MED/50'],
    '07 - Scienze agrarie e veterinarie': ['AGR/01','AGR/02','AGR/03','AGR/04','AGR/05','AGR/06','AGR/07','AGR/08','AGR/09','AGR/10','AGR/11','AGR/12','AGR/13',
        'AGR/14','AGR/15','AGR/16','AGR/17','AGR/18','AGR/19','AGR/20', 'VET/01','VET/02','VET/03','VET/04','VET/05','VET/06',
        'VET/07','VET/08','VET/09','VET/10'],
    '08 - Ingegneria civile ed architettura': ['ICAR/01','ICAR/02','ICAR/03','ICAR/04','ICAR/05','ICAR/06','ICAR/07','ICAR/08','ICAR/09','ICAR/10','ICAR/11','ICAR/12',
        'ICAR/13','ICAR/14','ICAR/15','ICAR/16','ICAR/17','ICAR/18','ICAR/19','ICAR/20','ICAR/21','ICAR/22'],
    '09 - Ingegneria industriale e dell\'informazione': ['ING-IND/01','ING-IND/02','ING-IND/03','ING-IND/04','ING-IND/05','ING-IND/06','ING-IND/07','ING-IND/08','ING-IND/09',
        'ING-IND/10','ING-IND/11','ING-IND/12','ING-IND/13','ING-IND/14','ING-IND/15','ING-IND/16','ING-IND/17','ING-IND/18',
        'ING-IND/19','ING-IND/20','ING-IND/21','ING-IND/22','ING-IND/23','ING-IND/24','ING-IND/25','ING-IND/26','ING-IND/27',
        'ING-IND/28','ING-IND/29','ING-IND/30','ING-IND/31','ING-IND/32','ING-IND/33','ING-IND/34','ING-IND/35','ING-INF/01',
        'ING-INF/02','ING-INF/03','ING-INF/04','ING-INF/05','ING-INF/06','ING-INF/07'],
    '10 - Scienze dell\'antichità, filologico-letterarie e storico-artistiche': ['L-ANT/01','L-ANT/02','L-ANT/03','L-ANT/04','L-ANT/05','L-ANT/06','L-ANT/07','L-ANT/08','L-ANT/09','L-ANT/10',
        'L-ART/01','L-ART/02','L-ART/03','L-ART/04','L-ART/05','L-ART/06','L-ART/07','L-ART/08', 'L-FIL-LET/01','L-FIL-LET/02',
        'L-FIL-LET/03','L-FIL-LET/04','L-FIL-LET/05','L-FIL-LET/06','L-FIL-LET/07','L-FIL-LET/08','L-FIL-LET/09','L-FIL-LET/10',
        'L-FIL-LET/11','L-FIL-LET/12','L-FIL-LET/13','L-FIL-LET/14','L-FIL-LET/15','L-LIN/01','L-LIN/02','L-LIN/03','L-LIN/04',
        'L-LIN/05','L-LIN/06','L-LIN/07','L-LIN/08','L-LIN/09','L-LIN/10','L-LIN/11','L-LIN/12','L-LIN/13','L-LIN/14','L-LIN/15',
        'L-LIN/16','L-LIN/17','L-LIN/18','L-LIN/19','L-LIN/20','L-LIN/21','L-OR/01','L-OR/02','L-OR/03','L-OR/04','L-OR/05',
        'L-OR/06','L-OR/07','L-OR/08','L-OR/09','L-OR/10','L-OR/11','L-OR/12','L-OR/13','L-OR/14','L-OR/15','L-OR/16','L-OR/17',
        'L-OR/18','L-OR/19','L-OR/20','L-OR/21','L-OR/22','L-OR/23'],
    '11 - Scienze storiche, filosofiche, pedagogiche e psicologiche': ['M-DEA/01','M-EDF/01','M-EDF/02','M-FIL/01','M-FIL/02','M-FIL/03','M-FIL/04','M-FIL/05','M-FIL/06','M-FIL/07','M-FIL/08',
        'M-GGR/01','M-GGR/02','M-PED/01','M-PED/02','M-PED/03','M-PED/04','M-PSI/01','M-PSI/02','M-PSI/03','M-PSI/04','M-PSI/05',
        'M-PSI/06','M-PSI/07','M-PSI/08','M-STO/01','M-STO/02','M-STO/03','M-STO/04','M-STO/05','M-STO/06','M-STO/07','M-STO/08',
        'M-STO/09'],
    '12 - Scienze giuridiche': ['IUS/01','IUS/02','IUS/03','IUS/04','IUS/05','IUS/06','IUS/07','IUS/08','IUS/09','IUS/10','IUS/11','IUS/12','IUS/13',
        'IUS/14','IUS/15','IUS/16','IUS/17','IUS/18','IUS/19','IUS/20','IUS/21'],
    '13 - Scienze economiche e statistiche': ['SECS-P/01','SECS-P/02','SECS-P/03','SECS-P/04','SECS-P/05','SECS-P/06','SECS-P/07','SECS-P/08','SECS-P/09','SECS-P/10',
        'SECS-P/11','SECS-P/12','SECS-P/13','SECS-S/01','SECS-S/02','SECS-S/03','SECS-S/04','SECS-S/05','SECS-S/06'],
    '14 - Scienze politiche e sociali': ['SPS/01','SPS/02','SPS/03','SPS/04','SPS/05','SPS/06','SPS/07','SPS/08','SPS/09','SPS/10','SPS/11','SPS/12','SPS/13',
        'SPS/14','SPS/15']
}


VALUES_FASCIA = [
    'Assistente r.e.',
    'Associato',
    'Associato confermato',
    'Associato non confermato',
    'Incaricato',
    'Ordinario',
    'Ordinario r.e.',
    'Ricercatore',
    'Ricercatore a t.d. (art.1 comma 14 L. 230/05)',
    'Ricercatore a t.d. - t.defin. (L. 79/2022)',
    'Ricercatore a t.d. - t.defin. (art. 24 c.3-a L. 240/10)',
    'Ricercatore a t.d. - t.defin. (art. 24 c.3-b L. 240/10)',
    'Ricercatore a t.d. - t.pieno (L. 79/2022)',
    'Ricercatore a t.d. - t.pieno (art. 24 c.3-a L. 240/10)',
    'Ricercatore a t.d. - t.pieno (art. 24 c.3-b L. 240/10)',
    'Ricercatore non confermato',
    'Straordinario',
    'Straordinario tempo determinato'
]

VALUES_AREA = [
    '01 - Scienze matematiche e informatiche',
    '02 - Scienze fisiche',
    '03 - Scienze chimiche',
    '04 - Scienze della Terra',
    '05 - Scienze biologiche',
    '06 - Scienze mediche',
    '07 - Scienze agrarie e veterinarie',
    '08 - Ingegneria civile ed architettura',
    '09 - Ingegneria industriale e dell\'informazione',
    '10 - Scienze dell\'antichità, filologico-letterarie e storico-artistiche',
    '11 - Scienze storiche, filosofiche, pedagogiche e psicologiche',
    '12 - Scienze giuridiche',
    '13 - Scienze economiche e statistiche',
    '14 - Scienze politiche e sociali'
]

VALUES_SC = [
    '0',
    '00',
    '01/A1',
    '01/A2',
    '01/A3',
    '01/A4',
    '01/A5',
    '01/A6',
    '01/B1',
    '02/A1',
    '02/A2',
    '02/B1',
    '02/B2',
    '02/B3',
    '02/C1',
    '02/D1',
    '03/A1',
    '03/A2',
    '03/B1',
    '03/B2',
    '03/C1',
    '03/C2',
    '03/D1',
    '03/D2',
    '04/A1',
    '04/A2',
    '04/A3',
    '04/A4',
    '05/A1',
    '05/A2',
    '05/B1',
    '05/B2',
    '05/C1',
    '05/D1',
    '05/E1',
    '05/E2',
    '05/E3',
    '05/F1',
    '05/G1',
    '05/H1',
    '05/H2',
    '05/I1',
    '05/I2',
    '05/L1',
    '06/A1',
    '06/A2',
    '06/A3',
    '06/A4',
    '06/B1',
    '06/C1',
    '06/D1',
    '06/D2',
    '06/D3',
    '06/D4',
    '06/D5',
    '06/D6',
    '06/E1',
    '06/E2',
    '06/E3',
    '06/F1',
    '06/F2',
    '06/F3',
    '06/F4',
    '06/G1',
    '06/H1',
    '06/I1',
    '06/L1',
    '06/M1',
    '06/M2',
    '06/M3',
    '06/N1',
    '06/N2',
    '07/A1',
    '07/B1',
    '07/B2',
    '07/C1',
    '07/D1',
    '07/E1',
    '07/F1',
    '07/F2',
    '07/G1',
    '07/H1',
    '07/H2',
    '07/H3',
    '07/H4',
    '07/H5',
    '07/I1',
    '08/A1',
    '08/A2',
    '08/A3',
    '08/A4',
    '08/B1',
    '08/B2',
    '08/B3',
    '08/C1',
    '08/D1',
    '08/E1',
    '08/E2',
    '08/F1',
    '09/A1',
    '09/A2',
    '09/A3',
    '09/B1',
    '09/B2',
    '09/B3',
    '09/C1',
    '09/C2',
    '09/C3',
    '09/D1',
    '09/D2',
    '09/D3',
    '09/E1',
    '09/E2',
    '09/E3',
    '09/E4',
    '09/F1',
    '09/F2',
    '09/G1',
    '09/G2',
    '09/H1',
    '10/A1',
    '10/B1',
    '10/C1',
    '10/D1',
    '10/D2',
    '10/D3',
    '10/D4',
    '10/E1',
    '10/F1',
    '10/F2',
    '10/F3',
    '10/F4',
    '10/G1',
    '10/H1',
    '10/I1',
    '10/L1',
    '10/M1',
    '10/M2',
    '10/N1',
    '10/N2',
    '10/N3',
    '11/A1',
    '11/A2',
    '11/A3',
    '11/A4',
    '11/A5',
    '11/A6',
    '11/B1',
    '11/C1',
    '11/C2',
    '11/C3',
    '11/C4',
    '11/C5',
    '11/D1',
    '11/D2',
    '11/E1',
    '11/E2',
    '11/E3',
    '11/E4',
    '12/A1',
    '12/B1',
    '12/B2',
    '12/C1',
    '12/C2',
    '12/D1',
    '12/D2',
    '12/E1',
    '12/E2',
    '12/E3',
    '12/E4',
    '12/F1',
    '12/G1',
    '12/G2',
    '12/H1',
    '12/H2',
    '12/H3',
    '13/A1',
    '13/A2',
    '13/A3',
    '13/A4',
    '13/A5',
    '13/B1',
    '13/B2',
    '13/B3',
    '13/B4',
    '13/B5',
    '13/C1',
    '13/D1',
    '13/D2',
    '13/D3',
    '13/D4',
    '14/A1',
    '14/A2',
    '14/B1',
    '14/B2',
    '14/C1',
    '14/C2',
    '14/C3',
    '14/D1',
    'XXX0'
]

VALUES_SSD = [
    'AGR/01',
    'AGR/02',
    'AGR/03',
    'AGR/04',
    'AGR/05',
    'AGR/06',
    'AGR/07',
    'AGR/08',
    'AGR/09',
    'AGR/10',
    'AGR/11',
    'AGR/12',
    'AGR/13',
    'AGR/14',
    'AGR/15',
    'AGR/16',
    'AGR/17',
    'AGR/18',
    'AGR/19',
    'AGR/20',
    'BIO/01',
    'BIO/02',
    'BIO/03',
    'BIO/04',
    'BIO/05',
    'BIO/06',
    'BIO/07',
    'BIO/08',
    'BIO/09',
    'BIO/10',
    'BIO/11',
    'BIO/12',
    'BIO/13',
    'BIO/14',
    'BIO/15',
    'BIO/16',
    'BIO/17',
    'BIO/18',
    'BIO/19',
    'CHIM/01',
    'CHIM/02',
    'CHIM/03',
    'CHIM/04',
    'CHIM/05',
    'CHIM/06',
    'CHIM/07',
    'CHIM/08',
    'CHIM/09',
    'CHIM/10',
    'CHIM/11',
    'CHIM/12',
    'FIS/01',
    'FIS/02',
    'FIS/03',
    'FIS/04',
    'FIS/05',
    'FIS/06',
    'FIS/07',
    'FIS/08',
    'GEO/01',
    'GEO/02',
    'GEO/03',
    'GEO/04',
    'GEO/05',
    'GEO/06',
    'GEO/07',
    'GEO/08',
    'GEO/09',
    'GEO/10',
    'GEO/11',
    'GEO/12',
    'ICAR/01',
    'ICAR/02',
    'ICAR/03',
    'ICAR/04',
    'ICAR/05',
    'ICAR/06',
    'ICAR/07',
    'ICAR/08',
    'ICAR/09',
    'ICAR/10',
    'ICAR/11',
    'ICAR/12',
    'ICAR/13',
    'ICAR/14',
    'ICAR/15',
    'ICAR/16',
    'ICAR/17',
    'ICAR/18',
    'ICAR/19',
    'ICAR/20',
    'ICAR/21',
    'ICAR/22',
    'INF/01',
    'ING-IND/01',
    'ING-IND/02',
    'ING-IND/03',
    'ING-IND/04',
    'ING-IND/05',
    'ING-IND/06',
    'ING-IND/07',
    'ING-IND/08',
    'ING-IND/09',
    'ING-IND/10',
    'ING-IND/11',
    'ING-IND/12',
    'ING-IND/13',
    'ING-IND/14',
    'ING-IND/15',
    'ING-IND/16',
    'ING-IND/17',
    'ING-IND/18',
    'ING-IND/19',
    'ING-IND/20',
    'ING-IND/21',
    'ING-IND/22',
    'ING-IND/23',
    'ING-IND/24',
    'ING-IND/25',
    'ING-IND/26',
    'ING-IND/27',
    'ING-IND/28',
    'ING-IND/29',
    'ING-IND/30',
    'ING-IND/31',
    'ING-IND/32',
    'ING-IND/33',
    'ING-IND/34',
    'ING-IND/35',
    'ING-INF/01',
    'ING-INF/02',
    'ING-INF/03',
    'ING-INF/04',
    'ING-INF/05',
    'ING-INF/06',
    'ING-INF/07',
    'IUS/01',
    'IUS/02',
    'IUS/03',
    'IUS/04',
    'IUS/05',
    'IUS/06',
    'IUS/07',
    'IUS/08',
    'IUS/09',
    'IUS/10',
    'IUS/11',
    'IUS/12',
    'IUS/13',
    'IUS/14',
    'IUS/15',
    'IUS/16',
    'IUS/17',
    'IUS/18',
    'IUS/19',
    'IUS/20',
    'IUS/21',
    'L-ANT/01',
    'L-ANT/02',
    'L-ANT/03',
    'L-ANT/04',
    'L-ANT/05',
    'L-ANT/06',
    'L-ANT/07',
    'L-ANT/08',
    'L-ANT/09',
    'L-ANT/10',
    'L-ART/01',
    'L-ART/02',
    'L-ART/03',
    'L-ART/04',
    'L-ART/05',
    'L-ART/06',
    'L-ART/07',
    'L-ART/08',
    'L-FIL-LET/01',
    'L-FIL-LET/02',
    'L-FIL-LET/03',
    'L-FIL-LET/04',
    'L-FIL-LET/05',
    'L-FIL-LET/06',
    'L-FIL-LET/07',
    'L-FIL-LET/08',
    'L-FIL-LET/09',
    'L-FIL-LET/10',
    'L-FIL-LET/11',
    'L-FIL-LET/12',
    'L-FIL-LET/13',
    'L-FIL-LET/14',
    'L-FIL-LET/15',
    'L-LIN/01',
    'L-LIN/02',
    'L-LIN/03',
    'L-LIN/04',
    'L-LIN/05',
    'L-LIN/06',
    'L-LIN/07',
    'L-LIN/08',
    'L-LIN/09',
    'L-LIN/10',
    'L-LIN/11',
    'L-LIN/12',
    'L-LIN/13',
    'L-LIN/14',
    'L-LIN/15',
    'L-LIN/16',
    'L-LIN/17',
    'L-LIN/18',
    'L-LIN/19',
    'L-LIN/20',
    'L-LIN/21',
    'L-OR/01',
    'L-OR/02',
    'L-OR/03',
    'L-OR/04',
    'L-OR/05',
    'L-OR/06',
    'L-OR/07',
    'L-OR/08',
    'L-OR/09',
    'L-OR/10',
    'L-OR/11',
    'L-OR/12',
    'L-OR/13',
    'L-OR/14',
    'L-OR/15',
    'L-OR/16',
    'L-OR/17',
    'L-OR/18',
    'L-OR/19',
    'L-OR/20',
    'L-OR/21',
    'L-OR/22',
    'L-OR/23',
    'M-DEA/01',
    'M-EDF/01',
    'M-EDF/02',
    'M-FIL/01',
    'M-FIL/02',
    'M-FIL/03',
    'M-FIL/04',
    'M-FIL/05',
    'M-FIL/06',
    'M-FIL/07',
    'M-FIL/08',
    'M-GGR/01',
    'M-GGR/02',
    'M-PED/01',
    'M-PED/02',
    'M-PED/03',
    'M-PED/04',
    'M-PSI/01',
    'M-PSI/02',
    'M-PSI/03',
    'M-PSI/04',
    'M-PSI/05',
    'M-PSI/06',
    'M-PSI/07',
    'M-PSI/08',
    'M-STO/01',
    'M-STO/02',
    'M-STO/03',
    'M-STO/04',
    'M-STO/05',
    'M-STO/06',
    'M-STO/07',
    'M-STO/08',
    'M-STO/09',
    'MAT/01',
    'MAT/02',
    'MAT/03',
    'MAT/04',
    'MAT/05',
    'MAT/06',
    'MAT/07',
    'MAT/08',
    'MAT/09',
    'MED/01',
    'MED/02',
    'MED/03',
    'MED/04',
    'MED/05',
    'MED/06',
    'MED/07',
    'MED/08',
    'MED/09',
    'MED/10',
    'MED/11',
    'MED/12',
    'MED/13',
    'MED/14',
    'MED/15',
    'MED/16',
    'MED/17',
    'MED/18',
    'MED/19',
    'MED/20',
    'MED/21',
    'MED/22',
    'MED/23',
    'MED/24',
    'MED/25',
    'MED/26',
    'MED/27',
    'MED/28',
    'MED/29',
    'MED/30',
    'MED/31',
    'MED/32',
    'MED/33',
    'MED/34',
    'MED/35',
    'MED/36',
    'MED/37',
    'MED/38',
    'MED/39',
    'MED/40',
    'MED/41',
    'MED/42',
    'MED/43',
    'MED/44',
    'MED/45',
    'MED/46',
    'MED/47',
    'MED/48',
    'MED/49',
    'MED/50',
    'SECS-P/01',
    'SECS-P/02',
    'SECS-P/03',
    'SECS-P/04',
    'SECS-P/05',
    'SECS-P/06',
    'SECS-P/07',
    'SECS-P/08',
    'SECS-P/09',
    'SECS-P/10',
    'SECS-P/11',
    'SECS-P/12',
    'SECS-P/13',
    'SECS-S/01',
    'SECS-S/02',
    'SECS-S/03',
    'SECS-S/04',
    'SECS-S/05',
    'SECS-S/06',
    'SPS/01',
    'SPS/02',
    'SPS/03',
    'SPS/04',
    'SPS/05',
    'SPS/06',
    'SPS/07',
    'SPS/08',
    'SPS/09',
    'SPS/10',
    'SPS/11',
    'SPS/12',
    'SPS/13',
    'SPS/14',
    'VET/01',
    'VET/02',
    'VET/03',
    'VET/04',
    'VET/05',
    'VET/06',
    'VET/07',
    'VET/08',
    'VET/09',
    'VET/10',
    'XXX0'
]