export default class Values {

    // anni di cui abbiamo i dati
    static YEAR_START = 2000;
    static YEAR_END = 2024;


    // nomi colonne
    static FIELD_ATENEO = "Ateneo";
    static FIELD_NOME = "Cognome e Nome";
    static FIELD_FACOLTA = "Facoltà";
    static FIELD_FASCIA = "Fascia";
    static FIELD_GENERE = "Genere";
    static FIELD_SC = "S.C.";
    static FIELD_SSD = "S.S.D.";
    static FIELD_STRUTTURA = "Struttura di afferenza";
    static FIELD_AREA = "area";
    static FIELD_YEAR = "year";


    // source:
    // http://www.inaf.it/it/documenti/adr-aree-cun-e-ssd
    static VALUES_SSD_PER_AREA = {
        '01 - Scienze matematiche e informatiche': ['INF/01', 'MAT/01', 'MAT/02', 'MAT/03', 'MAT/04', 'MAT/05', 'MAT/06', 'MAT/07', 'MAT/08', 'MAT/09'],
        '02 - Scienze fisiche': ['FIS/01', 'FIS/02', 'FIS/03', 'FIS/04', 'FIS/05', 'FIS/06', 'FIS/07', 'FIS/08'],
        '03 - Scienze chimiche': ['CHIM/01', 'CHIM/02', 'CHIM/03', 'CHIM/04', 'CHIM/05', 'CHIM/06', 'CHIM/07', 'CHIM/08', 'CHIM/09', 'CHIM/10', 'CHIM/11',
            'CHIM/12'],
        '04 - Scienze della Terra': ['GEO/01', 'GEO/02', 'GEO/03', 'GEO/04', 'GEO/05', 'GEO/06', 'GEO/07', 'GEO/08', 'GEO/09', 'GEO/10', 'GEO/11', 'GEO/12'],
        '05 - Scienze biologiche': ['BIO/01', 'BIO/02', 'BIO/03', 'BIO/04', 'BIO/05', 'BIO/06', 'BIO/07', 'BIO/08', 'BIO/09', 'BIO/10', 'BIO/11', 'BIO/12',
            'BIO/13', 'BIO/14', 'BIO/15', 'BIO/16', 'BIO/17', 'BIO/18', 'BIO/19'],
        '06 - Scienze mediche': ['MED/01','MED/02','MED/03','MED/04','MED/05','MED/06','MED/07','MED/08','MED/09','MED/10','MED/11','MED/12','MED/13',
            'MED/14','MED/15','MED/16','MED/17','MED/18','MED/19','MED/20','MED/21','MED/22','MED/23','MED/24','MED/25','MED/26',
            'MED/27','MED/28','MED/29','MED/30','MED/31','MED/32','MED/33','MED/34','MED/35','MED/36','MED/37','MED/38','MED/39',
            'MED/40','MED/41','MED/42','MED/43','MED/44','MED/45','MED/46','MED/47','MED/48','MED/49','MED/50'],
        '07 - Scienze agrarie e veterinarie': ['AGR/01','AGR/02','AGR/03','AGR/04','AGR/05','AGR/06','AGR/07','AGR/08','AGR/09','AGR/10','AGR/11','AGR/12','AGR/13',
            'AGR/14','AGR/15','AGR/16','AGR/17','AGR/18','AGR/19','AGR/20', 'VET/01','VET/02','VET/03','VET/04','VET/05','VET/06',
            'VET/07','VET/08','VET/09','VET/10'],
        '08 - Ingegneria civile ed architettura': ['ICAR/01','ICAR/02','ICAR/03','ICAR/04','ICAR/05','ICAR/06','ICAR/07','ICAR/08','ICAR/09','ICAR/10','ICAR/11','ICAR/12',
            'ICAR/13','ICAR/14','ICAR/15','ICAR/16','ICAR/17','ICAR/18','ICAR/19','ICAR/20','ICAR/21','ICAR/22'],
        '09 - Ingegneria industriale e dell\'informazione': ['ING-IND/01','ING-IND/02','ING-IND/03','ING-IND/04','ING-IND/05','ING-IND/06','ING-IND/07','ING-IND/08','ING-IND/09',
            'ING-IND/10','ING-IND/11','ING-IND/12','ING-IND/13','ING-IND/14','ING-IND/15','ING-IND/16','ING-IND/17','ING-IND/18',
            'ING-IND/19','ING-IND/20','ING-IND/21','ING-IND/22','ING-IND/23','ING-IND/24','ING-IND/25','ING-IND/26','ING-IND/27',
            'ING-IND/28','ING-IND/29','ING-IND/30','ING-IND/31','ING-IND/32','ING-IND/33','ING-IND/34','ING-IND/35','ING-INF/01',
            'ING-INF/02','ING-INF/03','ING-INF/04','ING-INF/05','ING-INF/06','ING-INF/07'],
        '10 - Scienze dell\'antichità, filologico-letterarie e storico-artistiche': ['L-ANT/01','L-ANT/02','L-ANT/03','L-ANT/04','L-ANT/05','L-ANT/06','L-ANT/07','L-ANT/08','L-ANT/09','L-ANT/10',
            'L-ART/01','L-ART/02','L-ART/03','L-ART/04','L-ART/05','L-ART/06','L-ART/07','L-ART/08', 'L-FIL-LET/01','L-FIL-LET/02',
            'L-FIL-LET/03','L-FIL-LET/04','L-FIL-LET/05','L-FIL-LET/06','L-FIL-LET/07','L-FIL-LET/08','L-FIL-LET/09','L-FIL-LET/10',
            'L-FIL-LET/11','L-FIL-LET/12','L-FIL-LET/13','L-FIL-LET/14','L-FIL-LET/15','L-LIN/01','L-LIN/02','L-LIN/03','L-LIN/04',
            'L-LIN/05','L-LIN/06','L-LIN/07','L-LIN/08','L-LIN/09','L-LIN/10','L-LIN/11','L-LIN/12','L-LIN/13','L-LIN/14','L-LIN/15',
            'L-LIN/16','L-LIN/17','L-LIN/18','L-LIN/19','L-LIN/20','L-LIN/21','L-OR/01','L-OR/02','L-OR/03','L-OR/04','L-OR/05',
            'L-OR/06','L-OR/07','L-OR/08','L-OR/09','L-OR/10','L-OR/11','L-OR/12','L-OR/13','L-OR/14','L-OR/15','L-OR/16','L-OR/17',
            'L-OR/18','L-OR/19','L-OR/20','L-OR/21','L-OR/22','L-OR/23'],
        '11 - Scienze storiche, filosofiche, pedagogiche e psicologiche': ['M-DEA/01','M-EDF/01','M-EDF/02','M-FIL/01','M-FIL/02','M-FIL/03','M-FIL/04','M-FIL/05','M-FIL/06','M-FIL/07','M-FIL/08',
            'M-GGR/01','M-GGR/02','M-PED/01','M-PED/02','M-PED/03','M-PED/04','M-PSI/01','M-PSI/02','M-PSI/03','M-PSI/04','M-PSI/05',
            'M-PSI/06','M-PSI/07','M-PSI/08','M-STO/01','M-STO/02','M-STO/03','M-STO/04','M-STO/05','M-STO/06','M-STO/07','M-STO/08',
            'M-STO/09'],
        '12 - Scienze giuridiche': ['IUS/01','IUS/02','IUS/03','IUS/04','IUS/05','IUS/06','IUS/07','IUS/08','IUS/09','IUS/10','IUS/11','IUS/12','IUS/13',
            'IUS/14','IUS/15','IUS/16','IUS/17','IUS/18','IUS/19','IUS/20','IUS/21'],
        '13 - Scienze economiche e statistiche': ['SECS-P/01','SECS-P/02','SECS-P/03','SECS-P/04','SECS-P/05','SECS-P/06','SECS-P/07','SECS-P/08','SECS-P/09','SECS-P/10',
            'SECS-P/11','SECS-P/12','SECS-P/13','SECS-S/01','SECS-S/02','SECS-S/03','SECS-S/04','SECS-S/05','SECS-S/06'],
        '14 - Scienze politiche e sociali': ['SPS/01','SPS/02','SPS/03','SPS/04','SPS/05','SPS/06','SPS/07','SPS/08','SPS/09','SPS/10','SPS/11','SPS/12','SPS/13',
            'SPS/14','SPS/15']
    };


    static VALUES_ATENEO = [
        'BARI',
        'BASILICATA',
        'BERGAMO',
        'BOLOGNA',
        'BRESCIA',
        'Bocconi MILANO',
        '"Ca\' Foscari" VENEZIA',
        'CAGLIARI',
        'CAMERINO',
        'CAMPANIA - "L. VANVITELLI"',
        'CASD - Scuola Superiore',
        'CASSINO e LAZIO MERIDIONALE',
        'CATANIA',
        'CATANZARO',
        'CHIETI-PESCARA',
        'Cattolica del Sacro Cuore',
        'della CALABRIA',
        'EUROPEA di ROMA',
        'FERRARA',
        'FIRENZE',
        'FOGGIA',
        'GENOVA',
        'Gran Sasso Science Institute',
        'HUMANITAS University',
        'I.U.S.S. - PAVIA',
        'INSUBRIA',
        'IULM - MILANO',
        'L\'AQUILA',
        '"L\'Orientale" di NAPOLI',
        'LINK CAMPUS',
        'LIUC - CASTELLANZA',
        'LUM "Giuseppe Degennaro"',
        'Libera Univ. "Maria SS.Assunta"-LUMSA - ROMA',
        'Libera Università di BOLZANO',
        'Luiss Guido Carli',
        'MACERATA',
        'MESSINA',
        'MILANO',
        'MILANO-BICOCCA',
        'MODENA e REGGIO EMILIA',
        'MOLISE',
        'Mediterranea di REGGIO CALABRIA',
        'Napoli Federico II',
        'PADOVA',
        'PALERMO',
        'PARMA',
        '"Parthenope" di NAPOLI',
        'PAVIA',
        'PERUGIA',
        'PIEMONTE ORIENTALE',
        'PISA',
        'Politecnica delle MARCHE',
        'Politecnico di BARI',
        'Politecnico di MILANO',
        'Politecnico di TORINO',
        'ROMA "Foro Italico"',
        'ROMA "La Sapienza"',
        'ROMA "Tor Vergata"',
        'ROMA TRE',
        'S. Raffaele MILANO',
        'SALENTO',
        'SALERNO',
        'SANNIO di BENEVENTO',
        'SASSARI',
        'SCIENZE GASTRONOMICHE',
        'SIENA',
        'SISSA - TRIESTE',
        'SUM - Ist. Italiano di SCIENZE UMANE FIRENZE',
        'Scuola IMT - LUCCA',
        'Scuola IMT Alti Studi LUCCA',
        'Scuola Normale Superiore di PISA',
        'Scuola Superiore Meridionale',
        'Scuola Superiore Sant\'Anna',
        'Stranieri REGGIO CALABRIA',
        'Stranieri di PERUGIA',
        'Stranieri di SIENA',
        'Suor Orsola Benincasa - NAPOLI',
        'TERAMO',
        'TORINO',
        'TRENTO',
        'TRIESTE',
        'TUSCIA',
        'UDINE',
        'UKE - Università Kore di ENNA',
        'UNICUSANO - Telematica Roma',
        'UNISR - San Raffaele',
        'UniCamillus',
        'UniCamillus - Saint Camillus International U',
        'Univ. "Campus Bio-Medico" di ROMA',
        'Univ. Studi GUGLIELMO MARCONI - Telematica',
        'Univ. Studi Internazionali di ROMA (UNINT)',
        'Univ. Telematica "E-CAMPUS"',
        'Univ. Telematica "GIUSTINO FORTUNATO"',
        'Univ. Telematica "LEONARDO da VINCI"',
        'Univ. Telematica "Universitas MERCATORUM"',
        'Univ. Telematica IUL',
        'Univ. Telematica Internazionale UNINETTUNO',
        'Univ. Telematica PEGASO',
        'Univ. Telematica San Raffaele Roma',
        'Univ. Telematica UNITELMA SAPIENZA',
        'Università IUAV di VENEZIA',
        'Università degli Studi di Roma UnitelmaSapie',
        'Urbino Carlo Bo',
        'VALLE D\'AOSTA',
        'VERONA'
    ];
    
    static VALUES_FACOLTA = [
        'Agraria',
        'Altre Strutture',
        'Architettura',
        'Architettura "Aldo Rossi"',
        'Architettura "Ludovico Quaroni"',
        'Architettura (*)',
        'Architettura Civile',
        'Architettura II',
        'Architettura III',
        'Architettura Valle Giulia',
        'Architettura e Design Industriale',
        'Architettura e Società',
        'Architettura-Urbanistica-Ambiente',
        'Arti e Turismo',
        'Arti e della Comunicazione',
        'Arti, Mercati e Patrimoni della Cultura',
        'Arti, Turismo e Mercati',
        'Arti, moda e turismo',
        'Beni Culturali',
        'Bioscienze e Biotecnologie',
        'Biotecnologie',
        'Centro Formazione "G.A.Colozza"',
        'Chimica Industriale',
        'Classe di Fisica e Classe di Matematica',
        'Classe di Scienze Mat. e Nat.',
        'Classe di Scienze Sociali',
        'Classe di Scienze Sperimentali',
        'Classe di Scienze Sperimentali e Applicate',
        'Classe di Scienze Umane',
        'Classe di Scienze e Tecnologie',
        'Comunicazione',
        'Comunicazione Relaz. Pubbliche e PubblicitÃ',
        'Conservazione dei Beni Culturali',
        'Design',
        'Design e Arti',
        'Economia',
        'Economia "Giorgio Fuà"',
        'Economia "Marco Biagi"',
        'Economia "Richard M. Goodwin"',
        'Economia (*)',
        'Economia (Sede di ForlÃ¬)',
        'Economia (Sede di Rimini)',
        'Economia II',
        'Economia III',
        'Economia Turismo, Ambiente e Cultura',
        'Economia e Giurisprudenza',
        'Economia e diritto',
        'Facoltà in Ambito di Economia',
        'Facoltà in Ambito di Giurisprudenza',
        'Facoltà in Ambito di Psicologia',
        'Facoltà in Ambito di Storia',
        'Farmacia',
        'Farmacia e Medicina',
        'Farmacia e Medicina (*)',
        'Farmacia e Scienze Nutrizione e Salute',
        'Filosof. Lett. Sc.Umanistiche e St.Orientali',
        'Filosof. Lett. Sc.Umanistiche e St.Orientali (*)',
        'Filosofia',
        'Gestione Delle Piccole e Medie Imprese',
        'Giurisprudenza',
        'Giurisprudenza (*)',
        'Giurisprudenza II',
        'Ing. Informazione, Informatica e Statistica',
        'Ing. Informazione, Informatica e Statistica (*)',
        'Ingegneria',
        'Ingegneria "Enzo Ferrari"',
        'Ingegneria Aeronautica e dello Spazio',
        'Ingegneria Civile e Industriale',
        'Ingegneria Civile e Industriale (*)',
        'Ingegneria Civile, Ambientale e Territoriale',
        'Ingegneria Edile-Architettura',
        'Ingegneria II',
        'Ingegneria II Sede di REGGIO EMILIA',
        'Ingegneria III',
        'Ingegneria IV',
        'Ingegneria Industriale',
        'Ingegneria V',
        'Ingegneria VI',
        'Ingegneria dei Processi Industriali',
        'Ingegneria dei Sistemi',
        'Ingegneria dell\'Informazione',
        'Ingegneria e Architettura',
        'Ingegneria e informatica',
        'Interfacoltà',
        'Interpret.Traduz.Studi Linguistici Cultur.',
        'Interpretariato e Traduzione',
        'Istituto di Scienze Umane e Sociali',
        'Lettere',
        'Lettere e Filosofia',
        'Lettere e Filosofia di Arezzo',
        'Lingua e Cultura Italiana',
        'Lingue Comunicaz. Territorio,Impresa Turismo',
        'Lingue e Comunicazione',
        'Lingue e Letterature Straniere',
        'Lingue e Letterature Straniere Moderne',
        'Lingue, Letterature e Culture Moderne',
        'Medicina Veterinaria',
        'Medicina e Chirurgia',
        'Medicina e Chirurgia II',
        'Medicina e Chirurgia II "San Luigi Gonzaga"',
        'Medicina e Odontoiatria',
        'Medicina e Odontoiatria (*)',
        'Medicina e Psicologia',
        'Medicina e Psicologia (*)',
        'Musicologia',
        'Pedagogia dell\'Infanzia',
        'Pianificazione del Territorio',
        'Psicologia',
        'Psicologia 2',
        'Psicologia e Scienze della Formazione',
        'Sc. Bancarie, Finanziarie, Assicurative',
        'Sc. Comunicazione e Economia',
        'Sc. Linguistiche e Letterature Straniere',
        'Sc. Politiche, Sociologia, Comunicazione',
        'Sc. Politiche, Sociologia, Comunicazione (*)',
        'Sc. Sup. Lingue Mod. Interpreti e Traduttori',
        'Sc. Tecniche Psicol. Relazioni Aiuto',
        'Sc.Comunicazione (Comunicaz.Economia Inform)',
        'Sc.Politecnica in Economia ed Organizzazione',
        'Sc.Umanistiche (Lett.Fil.-Lingue-Patr.Cult)',
        'Scienze',
        'Scienze Agrarie, Alimentari e Ambientali',
        'Scienze Agrarie, Ambientali e Alimentari',
        'Scienze Ambientali',
        'Scienze Biotecnologiche',
        'Scienze Cognitive',
        'Scienze Economia e Gestione Aziendale',
        'Scienze Economiche e Aziendali',
        'Scienze Economiche e Giuridiche',
        'Scienze Economiche e Sociali',
        'Scienze Gastronomiche',
        'Scienze Manageriali',
        'Scienze Mat. Fis. Nat. II',
        'Scienze Matematiche Fisiche e Naturali',
        'Scienze Matematiche Fisiche e Naturali (*)',
        'Scienze Motorie',
        'Scienze Motorie e del Benessere',
        'Scienze Nautiche',
        'Scienze Politiche',
        'Scienze Politiche II "Roberto Ruffilli"',
        'Scienze Politiche e Relazioni Internazionali',
        'Scienze Politiche e Sociali',
        'Scienze Sociali',
        'Scienze Sociali, Politiche e del Territorio',
        'Scienze Statistiche',
        'Scienze Umane e Sociali',
        'Scienze Umanistiche',
        'Scienze del Benessere',
        'Scienze del Farmaco per Ambiente e Salute',
        'Scienze dell\'Educazione Motoria',
        'Scienze dell\'Uomo e della Societa\'',
        'Scienze della Comunicazione',
        'Scienze della Comunicazione e dello Spett.',
        'Scienze della Formaz',
        'Scienze della Formazione',
        'Scienze della Formazione Primaria',
        'Scienze della Formazione d\'Area Mediterranea',
        'Scienze e Tecnologie',
        'Scienze e Tecnologie "P.Leonardi Cattolica"',
        'Scienze e Tecnologie Applicate',
        'Scienze e Tecnologie Informatiche',
        'Scienze tecnologiche e dell\'innovazione',
        'Scuola Ing. Astronautica',
        'Scuola Paleografia e Filologia Music.',
        'Scuola Spec. per Archivisti e Bibliotecari',
        'Scuola Superiore I.S.U.F.I.',
        'Scuola di A.attiv.did.UndergraduateGraduate',
        'Scuola di Ingegneria Aerospaziale',
        'Società e comunicazione',
        'Sociologia',
        'Ssis - Sc. Interateneo Special. Insegnanti',
        'Studi Arabo-Islamici e del Mediterraneo',
        'Studi Classici, Linguistici e Formazione',
        'Studi Islamici',
        'Studi Orientali',
        'Studi Politici Alta Formaz. Europea Mediter. "Jean Monnet"',
        'Turismo, Eventi e Territorio',
        'Valle d\'Aosta',
        'scienze della politica e dinamiche psico-soc',
        'scienze umane, della formazione e dello spor'
    ];
    
    static VALUES_FASCIA = [
        'Assistente r.e.',
        'Associato',
        'Associato confermato',
        'Associato non confermato',
        'Incaricato',
        'Ordinario',
        'Ordinario r.e.',
        'Ricercatore',
        'Ricercatore a t.d. (art.1 comma 14 L. 230/05)',
        'Ricercatore a t.d. - t.defin. (L. 79/2022)',
        'Ricercatore a t.d. - t.defin. (art. 24 c.3-a L. 240/10)',
        'Ricercatore a t.d. - t.defin. (art. 24 c.3-b L. 240/10)',
        'Ricercatore a t.d. - t.pieno (L. 79/2022)',
        'Ricercatore a t.d. - t.pieno (art. 24 c.3-a L. 240/10)',
        'Ricercatore a t.d. - t.pieno (art. 24 c.3-b L. 240/10)',
        'Ricercatore non confermato',
        'Straordinario',
        'Straordinario tempo determinato'
    ];
    
    static VALUES_AREA = [
        '01 - Scienze matematiche e informatiche',
        '02 - Scienze fisiche',
        '03 - Scienze chimiche',
        '04 - Scienze della Terra',
        '05 - Scienze biologiche',
        '06 - Scienze mediche',
        '07 - Scienze agrarie e veterinarie',
        '08 - Ingegneria civile ed architettura',
        '09 - Ingegneria industriale e dell\'informazione',
        '10 - Scienze dell\'antichità, filologico-letterarie e storico-artistiche',
        '11 - Scienze storiche, filosofiche, pedagogiche e psicologiche',
        '12 - Scienze giuridiche',
        '13 - Scienze economiche e statistiche',
        '14 - Scienze politiche e sociali'
    ];

    static VALUES_SC = [
        '0',
        '00',
        '01/A1',
        '01/A2',
        '01/A3',
        '01/A4',
        '01/A5',
        '01/A6',
        '01/B1',
        '02/A1',
        '02/A2',
        '02/B1',
        '02/B2',
        '02/B3',
        '02/C1',
        '02/D1',
        '03/A1',
        '03/A2',
        '03/B1',
        '03/B2',
        '03/C1',
        '03/C2',
        '03/D1',
        '03/D2',
        '04/A1',
        '04/A2',
        '04/A3',
        '04/A4',
        '05/A1',
        '05/A2',
        '05/B1',
        '05/B2',
        '05/C1',
        '05/D1',
        '05/E1',
        '05/E2',
        '05/E3',
        '05/F1',
        '05/G1',
        '05/H1',
        '05/H2',
        '05/I1',
        '05/I2',
        '05/L1',
        '06/A1',
        '06/A2',
        '06/A3',
        '06/A4',
        '06/B1',
        '06/C1',
        '06/D1',
        '06/D2',
        '06/D3',
        '06/D4',
        '06/D5',
        '06/D6',
        '06/E1',
        '06/E2',
        '06/E3',
        '06/F1',
        '06/F2',
        '06/F3',
        '06/F4',
        '06/G1',
        '06/H1',
        '06/I1',
        '06/L1',
        '06/M1',
        '06/M2',
        '06/M3',
        '06/N1',
        '06/N2',
        '07/A1',
        '07/B1',
        '07/B2',
        '07/C1',
        '07/D1',
        '07/E1',
        '07/F1',
        '07/F2',
        '07/G1',
        '07/H1',
        '07/H2',
        '07/H3',
        '07/H4',
        '07/H5',
        '07/I1',
        '08/A1',
        '08/A2',
        '08/A3',
        '08/A4',
        '08/B1',
        '08/B2',
        '08/B3',
        '08/C1',
        '08/D1',
        '08/E1',
        '08/E2',
        '08/F1',
        '09/A1',
        '09/A2',
        '09/A3',
        '09/B1',
        '09/B2',
        '09/B3',
        '09/C1',
        '09/C2',
        '09/C3',
        '09/D1',
        '09/D2',
        '09/D3',
        '09/E1',
        '09/E2',
        '09/E3',
        '09/E4',
        '09/F1',
        '09/F2',
        '09/G1',
        '09/G2',
        '09/H1',
        '10/A1',
        '10/B1',
        '10/C1',
        '10/D1',
        '10/D2',
        '10/D3',
        '10/D4',
        '10/E1',
        '10/F1',
        '10/F2',
        '10/F3',
        '10/F4',
        '10/G1',
        '10/H1',
        '10/I1',
        '10/L1',
        '10/M1',
        '10/M2',
        '10/N1',
        '10/N2',
        '10/N3',
        '11/A1',
        '11/A2',
        '11/A3',
        '11/A4',
        '11/A5',
        '11/A6',
        '11/B1',
        '11/C1',
        '11/C2',
        '11/C3',
        '11/C4',
        '11/C5',
        '11/D1',
        '11/D2',
        '11/E1',
        '11/E2',
        '11/E3',
        '11/E4',
        '12/A1',
        '12/B1',
        '12/B2',
        '12/C1',
        '12/C2',
        '12/D1',
        '12/D2',
        '12/E1',
        '12/E2',
        '12/E3',
        '12/E4',
        '12/F1',
        '12/G1',
        '12/G2',
        '12/H1',
        '12/H2',
        '12/H3',
        '13/A1',
        '13/A2',
        '13/A3',
        '13/A4',
        '13/A5',
        '13/B1',
        '13/B2',
        '13/B3',
        '13/B4',
        '13/B5',
        '13/C1',
        '13/D1',
        '13/D2',
        '13/D3',
        '13/D4',
        '14/A1',
        '14/A2',
        '14/B1',
        '14/B2',
        '14/C1',
        '14/C2',
        '14/C3',
        '14/D1',
        'XXX0'
    ];
    
    static VALUES_SSD = [
        'AGR/01',
        'AGR/02',
        'AGR/03',
        'AGR/04',
        'AGR/05',
        'AGR/06',
        'AGR/07',
        'AGR/08',
        'AGR/09',
        'AGR/10',
        'AGR/11',
        'AGR/12',
        'AGR/13',
        'AGR/14',
        'AGR/15',
        'AGR/16',
        'AGR/17',
        'AGR/18',
        'AGR/19',
        'AGR/20',
        'BIO/01',
        'BIO/02',
        'BIO/03',
        'BIO/04',
        'BIO/05',
        'BIO/06',
        'BIO/07',
        'BIO/08',
        'BIO/09',
        'BIO/10',
        'BIO/11',
        'BIO/12',
        'BIO/13',
        'BIO/14',
        'BIO/15',
        'BIO/16',
        'BIO/17',
        'BIO/18',
        'BIO/19',
        'CHIM/01',
        'CHIM/02',
        'CHIM/03',
        'CHIM/04',
        'CHIM/05',
        'CHIM/06',
        'CHIM/07',
        'CHIM/08',
        'CHIM/09',
        'CHIM/10',
        'CHIM/11',
        'CHIM/12',
        'FIS/01',
        'FIS/02',
        'FIS/03',
        'FIS/04',
        'FIS/05',
        'FIS/06',
        'FIS/07',
        'FIS/08',
        'GEO/01',
        'GEO/02',
        'GEO/03',
        'GEO/04',
        'GEO/05',
        'GEO/06',
        'GEO/07',
        'GEO/08',
        'GEO/09',
        'GEO/10',
        'GEO/11',
        'GEO/12',
        'ICAR/01',
        'ICAR/02',
        'ICAR/03',
        'ICAR/04',
        'ICAR/05',
        'ICAR/06',
        'ICAR/07',
        'ICAR/08',
        'ICAR/09',
        'ICAR/10',
        'ICAR/11',
        'ICAR/12',
        'ICAR/13',
        'ICAR/14',
        'ICAR/15',
        'ICAR/16',
        'ICAR/17',
        'ICAR/18',
        'ICAR/19',
        'ICAR/20',
        'ICAR/21',
        'ICAR/22',
        'INF/01',
        'ING-IND/01',
        'ING-IND/02',
        'ING-IND/03',
        'ING-IND/04',
        'ING-IND/05',
        'ING-IND/06',
        'ING-IND/07',
        'ING-IND/08',
        'ING-IND/09',
        'ING-IND/10',
        'ING-IND/11',
        'ING-IND/12',
        'ING-IND/13',
        'ING-IND/14',
        'ING-IND/15',
        'ING-IND/16',
        'ING-IND/17',
        'ING-IND/18',
        'ING-IND/19',
        'ING-IND/20',
        'ING-IND/21',
        'ING-IND/22',
        'ING-IND/23',
        'ING-IND/24',
        'ING-IND/25',
        'ING-IND/26',
        'ING-IND/27',
        'ING-IND/28',
        'ING-IND/29',
        'ING-IND/30',
        'ING-IND/31',
        'ING-IND/32',
        'ING-IND/33',
        'ING-IND/34',
        'ING-IND/35',
        'ING-INF/01',
        'ING-INF/02',
        'ING-INF/03',
        'ING-INF/04',
        'ING-INF/05',
        'ING-INF/06',
        'ING-INF/07',
        'IUS/01',
        'IUS/02',
        'IUS/03',
        'IUS/04',
        'IUS/05',
        'IUS/06',
        'IUS/07',
        'IUS/08',
        'IUS/09',
        'IUS/10',
        'IUS/11',
        'IUS/12',
        'IUS/13',
        'IUS/14',
        'IUS/15',
        'IUS/16',
        'IUS/17',
        'IUS/18',
        'IUS/19',
        'IUS/20',
        'IUS/21',
        'L-ANT/01',
        'L-ANT/02',
        'L-ANT/03',
        'L-ANT/04',
        'L-ANT/05',
        'L-ANT/06',
        'L-ANT/07',
        'L-ANT/08',
        'L-ANT/09',
        'L-ANT/10',
        'L-ART/01',
        'L-ART/02',
        'L-ART/03',
        'L-ART/04',
        'L-ART/05',
        'L-ART/06',
        'L-ART/07',
        'L-ART/08',
        'L-FIL-LET/01',
        'L-FIL-LET/02',
        'L-FIL-LET/03',
        'L-FIL-LET/04',
        'L-FIL-LET/05',
        'L-FIL-LET/06',
        'L-FIL-LET/07',
        'L-FIL-LET/08',
        'L-FIL-LET/09',
        'L-FIL-LET/10',
        'L-FIL-LET/11',
        'L-FIL-LET/12',
        'L-FIL-LET/13',
        'L-FIL-LET/14',
        'L-FIL-LET/15',
        'L-LIN/01',
        'L-LIN/02',
        'L-LIN/03',
        'L-LIN/04',
        'L-LIN/05',
        'L-LIN/06',
        'L-LIN/07',
        'L-LIN/08',
        'L-LIN/09',
        'L-LIN/10',
        'L-LIN/11',
        'L-LIN/12',
        'L-LIN/13',
        'L-LIN/14',
        'L-LIN/15',
        'L-LIN/16',
        'L-LIN/17',
        'L-LIN/18',
        'L-LIN/19',
        'L-LIN/20',
        'L-LIN/21',
        'L-OR/01',
        'L-OR/02',
        'L-OR/03',
        'L-OR/04',
        'L-OR/05',
        'L-OR/06',
        'L-OR/07',
        'L-OR/08',
        'L-OR/09',
        'L-OR/10',
        'L-OR/11',
        'L-OR/12',
        'L-OR/13',
        'L-OR/14',
        'L-OR/15',
        'L-OR/16',
        'L-OR/17',
        'L-OR/18',
        'L-OR/19',
        'L-OR/20',
        'L-OR/21',
        'L-OR/22',
        'L-OR/23',
        'M-DEA/01',
        'M-EDF/01',
        'M-EDF/02',
        'M-FIL/01',
        'M-FIL/02',
        'M-FIL/03',
        'M-FIL/04',
        'M-FIL/05',
        'M-FIL/06',
        'M-FIL/07',
        'M-FIL/08',
        'M-GGR/01',
        'M-GGR/02',
        'M-PED/01',
        'M-PED/02',
        'M-PED/03',
        'M-PED/04',
        'M-PSI/01',
        'M-PSI/02',
        'M-PSI/03',
        'M-PSI/04',
        'M-PSI/05',
        'M-PSI/06',
        'M-PSI/07',
        'M-PSI/08',
        'M-STO/01',
        'M-STO/02',
        'M-STO/03',
        'M-STO/04',
        'M-STO/05',
        'M-STO/06',
        'M-STO/07',
        'M-STO/08',
        'M-STO/09',
        'MAT/01',
        'MAT/02',
        'MAT/03',
        'MAT/04',
        'MAT/05',
        'MAT/06',
        'MAT/07',
        'MAT/08',
        'MAT/09',
        'MED/01',
        'MED/02',
        'MED/03',
        'MED/04',
        'MED/05',
        'MED/06',
        'MED/07',
        'MED/08',
        'MED/09',
        'MED/10',
        'MED/11',
        'MED/12',
        'MED/13',
        'MED/14',
        'MED/15',
        'MED/16',
        'MED/17',
        'MED/18',
        'MED/19',
        'MED/20',
        'MED/21',
        'MED/22',
        'MED/23',
        'MED/24',
        'MED/25',
        'MED/26',
        'MED/27',
        'MED/28',
        'MED/29',
        'MED/30',
        'MED/31',
        'MED/32',
        'MED/33',
        'MED/34',
        'MED/35',
        'MED/36',
        'MED/37',
        'MED/38',
        'MED/39',
        'MED/40',
        'MED/41',
        'MED/42',
        'MED/43',
        'MED/44',
        'MED/45',
        'MED/46',
        'MED/47',
        'MED/48',
        'MED/49',
        'MED/50',
        'SECS-P/01',
        'SECS-P/02',
        'SECS-P/03',
        'SECS-P/04',
        'SECS-P/05',
        'SECS-P/06',
        'SECS-P/07',
        'SECS-P/08',
        'SECS-P/09',
        'SECS-P/10',
        'SECS-P/11',
        'SECS-P/12',
        'SECS-P/13',
        'SECS-S/01',
        'SECS-S/02',
        'SECS-S/03',
        'SECS-S/04',
        'SECS-S/05',
        'SECS-S/06',
        'SPS/01',
        'SPS/02',
        'SPS/03',
        'SPS/04',
        'SPS/05',
        'SPS/06',
        'SPS/07',
        'SPS/08',
        'SPS/09',
        'SPS/10',
        'SPS/11',
        'SPS/12',
        'SPS/13',
        'SPS/14',
        'VET/01',
        'VET/02',
        'VET/03',
        'VET/04',
        'VET/05',
        'VET/06',
        'VET/07',
        'VET/08',
        'VET/09',
        'VET/10',
        'XXX0'
    ];
}